export const tabs = [
    { id: "all", label: "All Tasks" },
    { id: "inquiries", label: "Inquiries (56)" },
    { id: "bookings", label: "Bookings (23)" },
    { id: "requests", label: "Requests (23)" },
    { id: "invoices", label: "Invoices (23)" },
  ];
  
  export const initialTasks = [
    {
      id: "TA- 002",
      assignee: "Annette Black",
      summary: "Replacement Worn-Out Drive Belts",
      category: "Work Order",
      messageType: "SMS",
      status: "Resolved",
      lastUpdated: "11:30 AM\n24 Aug 2014",
    },
    {
      id: "TA- 002",
      assignee: "Annette Black",
      summary: "Replacement Worn-Out Drive Belts",
      category: "Work Order",
      messageType: "SMS",
      status: "Resolved",
      lastUpdated: "11:30 AM\n24 Aug 2014",
    },
    {
      id: "TA- 002",
      assignee: "Vuejs Courses",
      summary: "Lubrication Conveyor Bearings",
      category: "Inquiries",
      messageType: "SMS",
      status: "Needs Reply",
      lastUpdated: "11:30 AM\n24 Aug 2014",
    },
    {
      id: "TA- 002",
      assignee: "Leslie Alexander",
      summary: "Overhaul Hydraulic Press System",
      category: "Work Order",
      messageType: "SMS",
      status: "Not Started",
      lastUpdated: "11:30 AM\n24 Aug 2014",
    },
    {
      id: "TA- 001",
      assignee: "Cameron Williamson",
      summary: "Emergency Repair Cooling System...",
      category: "Inquiries",
      messageType: "CALL",
      status: "Needs Reply",
      lastUpdated: "11:30 AM\n24 Aug 2014",
    },
    {
      id: "TA- 002",
      assignee: "Aubrey",
      summary: "Repair Cracks On The Walls",
      category: "Work Order",
      messageType: "CALL",
      status: "Resolved",
      lastUpdated: "11:30 AM\n24 Aug 2014",
    },
    {
      id: "TA- 002",
      assignee: "Aubrey",
      summary: "Repair Cracks On The Walls",
      category: "Work Order",
      messageType: "CALL",
      status: "Resolved",
      lastUpdated: "11:30 AM\n24 Aug 2014",
    },
    {
      id: "TA- 001",
      assignee: "Marvin McKinney",
      summary: "Maintenance Of HVACV System",
      category: "Inquiries",
      messageType: "SMS",
      status: "Needs Reply",
      lastUpdated: "11:30 AM\n24 Aug 2014",
    },
    {
      id: "TA- 002",
      assignee: "Esther Howard",
      summary: "Fire Extinguisher, Repairs",
      category: "Work Order",
      messageType: "SMS",
      status: "Not Started",
      lastUpdated: "11:30 AM\n24 Aug 2014",
    },
    {
      id: "TA- 002",
      assignee: "Annette Black",
      summary: "A/C Vents Leaks Water",
      category: "Work Order",
      messageType: "SMS",
      status: "Resolved",
      lastUpdated: "11:30 AM\n24 Aug 2014",
    },
    {
      id: "TA- 001",
      assignee: "Jane Cooper",
      summary: "Equipment Upgrade PLC Control...",
      category: "Inquiries",
      messageType: "CALL",
      status: "Needs Reply",
      lastUpdated: "11:30 AM\n24 Aug 2014",
    },
    {
      id: "TA- 001",
      assignee: "Jane Cooper",
      summary: "Equipment Upgrade PLC Control...",
      category: "Inquiries",
      messageType: "CALL",
      status: "Needs Reply",
      lastUpdated: "11:30 AM\n24 Aug 2014",
    },
  ];