import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/CustomComponents/Sidebar";
import Header from "@/components/CustomComponents/Header";
import { Inter } from 'next/font/google'
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <div className="flex  h-screen bg-white overflow-hidden">
          {/* Sidebar */}

          <Sidebar />
          {/* Main content */}
          <main className="flex-1  overflow-y-auto">
            {/* Header */}
            <Header />

            {/* Content */}
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
